import unittest
import numpy as np
from keras import layers
from keras.models import Model
from keras.engine import Input
from keras.layers import Dense


class TestsFailing(unittest.TestCase):

    def test_diversity_1(self):
        input_shape = (1, 879)
        input_layer = Input(shape=input_shape)
        A = Dense(12, name='layer_a')
        r1 = layers.Reshape((879,))(input_layer)
        Aout1 = A(r1)
        r2 = layers.Reshape((36,))(A(input_layer))
        Aout2 = A(r2)
        c1 = layers.concatenate([Aout2, Aout1])
        output = Dense(2, name='layer_b')(c1)
        M = Model(inputs=input_layer, outputs=output)
        x_val = np.random.random((10,) + input_shape)
        output_val = M.predict(x_val)
        config = M.get_config()
        weights = M.get_weights()
        M2 = Model.from_config(config)
        M2.set_weights(weights)
        output_val_2 = M2.predict(x_val)
        np.testing.assert_allclose(output_val, output_val_2, atol=1e-06)

    def test_diversity_2(self):
        input_shape = (1, 736)
        input_layer = Input(shape=input_shape)
        A = Dense(12, name='layer_a')
        r1 = layers.Reshape((736,))(input_layer)
        Aout1 = A(r1)
        r2 = layers.Reshape((146,))(A(input_layer))
        Aout2 = A(r2)
        c1 = layers.concatenate([Aout2, Aout1])
        output = Dense(2, name='layer_b')(c1)
        M = Model(inputs=input_layer, outputs=output)
        x_val = np.random.random((10,) + input_shape)
        output_val = M.predict(x_val)
        config = M.get_config()
        weights = M.get_weights()
        M2 = Model.from_config(config)
        M2.set_weights(weights)
        output_val_2 = M2.predict(x_val)
        np.testing.assert_allclose(output_val, output_val_2, atol=1e-06)

    def test_diversity_3(self):
        input_shape = (1, 539)
        input_layer = Input(shape=input_shape)
        A = Dense(12, name='layer_a')
        r1 = layers.Reshape((539,))(input_layer)
        Aout1 = A(r1)
        r2 = layers.Reshape((518,))(A(input_layer))
        Aout2 = A(r2)
        c1 = layers.concatenate([Aout2, Aout1])
        output = Dense(2, name='layer_b')(c1)
        M = Model(inputs=input_layer, outputs=output)
        x_val = np.random.random((10,) + input_shape)
        output_val = M.predict(x_val)
        config = M.get_config()
        weights = M.get_weights()
        M2 = Model.from_config(config)
        M2.set_weights(weights)
        output_val_2 = M2.predict(x_val)
        np.testing.assert_allclose(output_val, output_val_2, atol=1e-06)

    def test_diversity_4(self):
        input_shape = (1, 862)
        input_layer = Input(shape=input_shape)
        A = Dense(12, name='layer_a')
        r1 = layers.Reshape((862,))(input_layer)
        Aout1 = A(r1)
        r2 = layers.Reshape((664,))(A(input_layer))
        Aout2 = A(r2)
        c1 = layers.concatenate([Aout2, Aout1])
        output = Dense(2, name='layer_b')(c1)
        M = Model(inputs=input_layer, outputs=output)
        x_val = np.random.random((10,) + input_shape)
        output_val = M.predict(x_val)
        config = M.get_config()
        weights = M.get_weights()
        M2 = Model.from_config(config)
        M2.set_weights(weights)
        output_val_2 = M2.predict(x_val)
        np.testing.assert_allclose(output_val, output_val_2, atol=1e-06)

    def test_diversity_5(self):
        input_shape = (1, 556)
        input_layer = Input(shape=input_shape)
        A = Dense(12, name='layer_a')
        r1 = layers.Reshape((556,))(input_layer)
        Aout1 = A(r1)
        r2 = layers.Reshape((711,))(A(input_layer))
        Aout2 = A(r2)
        c1 = layers.concatenate([Aout2, Aout1])
        output = Dense(2, name='layer_b')(c1)
        M = Model(inputs=input_layer, outputs=output)
        x_val = np.random.random((10,) + input_shape)
        output_val = M.predict(x_val)
        config = M.get_config()
        weights = M.get_weights()
        M2 = Model.from_config(config)
        M2.set_weights(weights)
        output_val_2 = M2.predict(x_val)
        np.testing.assert_allclose(output_val, output_val_2, atol=1e-06)

    def test_diversity_6(self):
        input_shape = (1, 114)
        input_layer = Input(shape=input_shape)
        A = Dense(12, name='layer_a')
        r1 = layers.Reshape((114,))(input_layer)
        Aout1 = A(r1)
        r2 = layers.Reshape((368,))(A(input_layer))
        Aout2 = A(r2)
        c1 = layers.concatenate([Aout2, Aout1])
        output = Dense(2, name='layer_b')(c1)
        M = Model(inputs=input_layer, outputs=output)
        x_val = np.random.random((10,) + input_shape)
        output_val = M.predict(x_val)
        config = M.get_config()
        weights = M.get_weights()
        M2 = Model.from_config(config)
        M2.set_weights(weights)
        output_val_2 = M2.predict(x_val)
        np.testing.assert_allclose(output_val, output_val_2, atol=1e-06)

    def test_diversity_7(self):
        input_shape = (1, 808)
        input_layer = Input(shape=input_shape)
        A = Dense(12, name='layer_a')
        r1 = layers.Reshape((808,))(input_layer)
        Aout1 = A(r1)
        r2 = layers.Reshape((261,))(A(input_layer))
        Aout2 = A(r2)
        c1 = layers.concatenate([Aout2, Aout1])
        output = Dense(2, name='layer_b')(c1)
        M = Model(inputs=input_layer, outputs=output)
        x_val = np.random.random((10,) + input_shape)
        output_val = M.predict(x_val)
        config = M.get_config()
        weights = M.get_weights()
        M2 = Model.from_config(config)
        M2.set_weights(weights)
        output_val_2 = M2.predict(x_val)
        np.testing.assert_allclose(output_val, output_val_2, atol=1e-06)

    def test_diversity_8(self):
        input_shape = (1, 279)
        input_layer = Input(shape=input_shape)
        A = Dense(12, name='layer_a')
        r1 = layers.Reshape((279,))(input_layer)
        Aout1 = A(r1)
        r2 = layers.Reshape((552,))(A(input_layer))
        Aout2 = A(r2)
        c1 = layers.concatenate([Aout2, Aout1])
        output = Dense(2, name='layer_b')(c1)
        M = Model(inputs=input_layer, outputs=output)
        x_val = np.random.random((10,) + input_shape)
        output_val = M.predict(x_val)
        config = M.get_config()
        weights = M.get_weights()
        M2 = Model.from_config(config)
        M2.set_weights(weights)
        output_val_2 = M2.predict(x_val)
        np.testing.assert_allclose(output_val, output_val_2, atol=1e-06)

    def test_diversity_9(self):
        input_shape = (1, 466)
        input_layer = Input(shape=input_shape)
        A = Dense(12, name='layer_a')
        r1 = layers.Reshape((466,))(input_layer)
        Aout1 = A(r1)
        r2 = layers.Reshape((298,))(A(input_layer))
        Aout2 = A(r2)
        c1 = layers.concatenate([Aout2, Aout1])
        output = Dense(2, name='layer_b')(c1)
        M = Model(inputs=input_layer, outputs=output)
        x_val = np.random.random((10,) + input_shape)
        output_val = M.predict(x_val)
        config = M.get_config()
        weights = M.get_weights()
        M2 = Model.from_config(config)
        M2.set_weights(weights)
        output_val_2 = M2.predict(x_val)
        np.testing.assert_allclose(output_val, output_val_2, atol=1e-06)

    def test_diversity_10(self):
        input_shape = (1, 372)
        input_layer = Input(shape=input_shape)
        A = Dense(12, name='layer_a')
        r1 = layers.Reshape((372,))(input_layer)
        Aout1 = A(r1)
        r2 = layers.Reshape((571,))(A(input_layer))
        Aout2 = A(r2)
        c1 = layers.concatenate([Aout2, Aout1])
        output = Dense(2, name='layer_b')(c1)
        M = Model(inputs=input_layer, outputs=output)
        x_val = np.random.random((10,) + input_shape)
        output_val = M.predict(x_val)
        config = M.get_config()
        weights = M.get_weights()
        M2 = Model.from_config(config)
        M2.set_weights(weights)
        output_val_2 = M2.predict(x_val)
        np.testing.assert_allclose(output_val, output_val_2, atol=1e-06)




class TestsPassing(unittest.TestCase):

    def test_diversity_1(self):
        input_shape = (1, 415)
        input_layer = Input(shape=input_shape)
        A = Dense(12, name='layer_a')
        r1 = layers.Reshape((415,))(input_layer)
        Aout1 = A(r1)
        r2 = layers.Reshape((415,))(input_layer)
        Aout2 = A(r2)
        c1 = layers.concatenate([Aout2, Aout1])
        output = Dense(2, name='layer_b')(c1)
        M = Model(inputs=input_layer, outputs=output)
        x_val = np.random.random((10,) + input_shape)
        output_val = M.predict(x_val)
        config = M.get_config()
        weights = M.get_weights()
        M2 = Model.from_config(config)
        M2.set_weights(weights)
        output_val_2 = M2.predict(x_val)
        np.testing.assert_allclose(output_val, output_val_2, atol=1e-06)

    def test_diversity_2(self):
        input_shape = (1, 246)
        input_layer = Input(shape=input_shape)
        A = Dense(12, name='layer_a')
        r1 = layers.Reshape((246,))(input_layer)
        Aout1 = A(r1)
        r2 = layers.Reshape((246,))(input_layer)
        Aout2 = A(r2)
        c1 = layers.concatenate([Aout2, Aout1])
        output = Dense(2, name='layer_b')(c1)
        M = Model(inputs=input_layer, outputs=output)
        x_val = np.random.random((10,) + input_shape)
        output_val = M.predict(x_val)
        config = M.get_config()
        weights = M.get_weights()
        M2 = Model.from_config(config)
        M2.set_weights(weights)
        output_val_2 = M2.predict(x_val)
        np.testing.assert_allclose(output_val, output_val_2, atol=1e-06)

    def test_diversity_3(self):
        input_shape = (1, 380)
        input_layer = Input(shape=input_shape)
        A = Dense(12, name='layer_a')
        r1 = layers.Reshape((380,))(input_layer)
        Aout1 = A(r1)
        r2 = layers.Reshape((380,))(input_layer)
        Aout2 = A(r2)
        c1 = layers.concatenate([Aout2, Aout1])
        output = Dense(2, name='layer_b')(c1)
        M = Model(inputs=input_layer, outputs=output)
        x_val = np.random.random((10,) + input_shape)
        output_val = M.predict(x_val)
        config = M.get_config()
        weights = M.get_weights()
        M2 = Model.from_config(config)
        M2.set_weights(weights)
        output_val_2 = M2.predict(x_val)
        np.testing.assert_allclose(output_val, output_val_2, atol=1e-06)

    def test_diversity_4(self):
        input_shape = (1, 660)
        input_layer = Input(shape=input_shape)
        A = Dense(12, name='layer_a')
        r1 = layers.Reshape((660,))(input_layer)
        Aout1 = A(r1)
        r2 = layers.Reshape((660,))(input_layer)
        Aout2 = A(r2)
        c1 = layers.concatenate([Aout2, Aout1])
        output = Dense(2, name='layer_b')(c1)
        M = Model(inputs=input_layer, outputs=output)
        x_val = np.random.random((10,) + input_shape)
        output_val = M.predict(x_val)
        config = M.get_config()
        weights = M.get_weights()
        M2 = Model.from_config(config)
        M2.set_weights(weights)
        output_val_2 = M2.predict(x_val)
        np.testing.assert_allclose(output_val, output_val_2, atol=1e-06)

    def test_diversity_5(self):
        input_shape = (1, 560)
        input_layer = Input(shape=input_shape)
        A = Dense(12, name='layer_a')
        r1 = layers.Reshape((560,))(input_layer)
        Aout1 = A(r1)
        r2 = layers.Reshape((560,))(input_layer)
        Aout2 = A(r2)
        c1 = layers.concatenate([Aout2, Aout1])
        output = Dense(2, name='layer_b')(c1)
        M = Model(inputs=input_layer, outputs=output)
        x_val = np.random.random((10,) + input_shape)
        output_val = M.predict(x_val)
        config = M.get_config()
        weights = M.get_weights()
        M2 = Model.from_config(config)
        M2.set_weights(weights)
        output_val_2 = M2.predict(x_val)
        np.testing.assert_allclose(output_val, output_val_2, atol=1e-06)

    def test_diversity_6(self):
        input_shape = (1, 975)
        input_layer = Input(shape=input_shape)
        A = Dense(12, name='layer_a')
        r1 = layers.Reshape((975,))(input_layer)
        Aout1 = A(r1)
        r2 = layers.Reshape((975,))(input_layer)
        Aout2 = A(r2)
        c1 = layers.concatenate([Aout2, Aout1])
        output = Dense(2, name='layer_b')(c1)
        M = Model(inputs=input_layer, outputs=output)
        x_val = np.random.random((10,) + input_shape)
        output_val = M.predict(x_val)
        config = M.get_config()
        weights = M.get_weights()
        M2 = Model.from_config(config)
        M2.set_weights(weights)
        output_val_2 = M2.predict(x_val)
        np.testing.assert_allclose(output_val, output_val_2, atol=1e-06)

    def test_diversity_7(self):
        input_shape = (1, 621)
        input_layer = Input(shape=input_shape)
        A = Dense(12, name='layer_a')
        r1 = layers.Reshape((621,))(input_layer)
        Aout1 = A(r1)
        r2 = layers.Reshape((621,))(input_layer)
        Aout2 = A(r2)
        c1 = layers.concatenate([Aout2, Aout1])
        output = Dense(2, name='layer_b')(c1)
        M = Model(inputs=input_layer, outputs=output)
        x_val = np.random.random((10,) + input_shape)
        output_val = M.predict(x_val)
        config = M.get_config()
        weights = M.get_weights()
        M2 = Model.from_config(config)
        M2.set_weights(weights)
        output_val_2 = M2.predict(x_val)
        np.testing.assert_allclose(output_val, output_val_2, atol=1e-06)

    def test_diversity_8(self):
        input_shape = (1, 172)
        input_layer = Input(shape=input_shape)
        A = Dense(12, name='layer_a')
        r1 = layers.Reshape((172,))(input_layer)
        Aout1 = A(r1)
        r2 = layers.Reshape((172,))(input_layer)
        Aout2 = A(r2)
        c1 = layers.concatenate([Aout2, Aout1])
        output = Dense(2, name='layer_b')(c1)
        M = Model(inputs=input_layer, outputs=output)
        x_val = np.random.random((10,) + input_shape)
        output_val = M.predict(x_val)
        config = M.get_config()
        weights = M.get_weights()
        M2 = Model.from_config(config)
        M2.set_weights(weights)
        output_val_2 = M2.predict(x_val)
        np.testing.assert_allclose(output_val, output_val_2, atol=1e-06)

    def test_diversity_9(self):
        input_shape = (1, 239)
        input_layer = Input(shape=input_shape)
        A = Dense(12, name='layer_a')
        r1 = layers.Reshape((239,))(input_layer)
        Aout1 = A(r1)
        r2 = layers.Reshape((239,))(input_layer)
        Aout2 = A(r2)
        c1 = layers.concatenate([Aout2, Aout1])
        output = Dense(2, name='layer_b')(c1)
        M = Model(inputs=input_layer, outputs=output)
        x_val = np.random.random((10,) + input_shape)
        output_val = M.predict(x_val)
        config = M.get_config()
        weights = M.get_weights()
        M2 = Model.from_config(config)
        M2.set_weights(weights)
        output_val_2 = M2.predict(x_val)
        np.testing.assert_allclose(output_val, output_val_2, atol=1e-06)

    def test_diversity_10(self):
        input_shape = (1, 610)
        input_layer = Input(shape=input_shape)
        A = Dense(12, name='layer_a')
        r1 = layers.Reshape((610,))(input_layer)
        Aout1 = A(r1)
        r2 = layers.Reshape((610,))(input_layer)
        Aout2 = A(r2)
        c1 = layers.concatenate([Aout2, Aout1])
        output = Dense(2, name='layer_b')(c1)
        M = Model(inputs=input_layer, outputs=output)
        x_val = np.random.random((10,) + input_shape)
        output_val = M.predict(x_val)
        config = M.get_config()
        weights = M.get_weights()
        M2 = Model.from_config(config)
        M2.set_weights(weights)
        output_val_2 = M2.predict(x_val)
        np.testing.assert_allclose(output_val, output_val_2, atol=1e-06)
