import unittest
from luigi.scheduler import Scheduler, DONE

class TestsFailing(unittest.TestCase):

    def test_diversity_1(self):
        sch = Scheduler(**{'retry_delay': 100, 'remove_delay': 1000, 'worker_disconnect_delay': 10, 'disable_persist': 10, 'disable_window': 10, 'retry_count': 3, 'disable_hard_timeout': 3600})
        sch.add_task_batcher(worker='myworker', task_family='Aduwksoy', batched_args=['a'])
        sch.add_task(worker='myworker', task_id='Aduwksoy_a_1', family='Aduwksoy', params={'a': '1'}, batchable=True, deps=['DONE_duwksoy'])
        sch.add_task(worker='myworker', task_id='Aduwksoy_a_2', family='Aduwksoy', params={'a': '2'}, batchable=True, deps=['NOTDONE_duwksoy'])
        sch.add_task(worker='myworker', task_id='Aduwksoy_a_3', family='Aduwksoy', params={'a': '3'}, batchable=True, deps=['DONE_duwksoy'])
        sch.add_task(worker='myworker', task_id='Aduwksoy_a_4', family='Aduwksoy', params={'a': '4'}, batchable=True, deps=['DONE_duwksoy'])
        sch.add_task(worker='myworker', task_id='NOTDONE_duwksoy', runnable=False)
        sch.add_task(worker='myworker', task_id='DONE_duwksoy', status=DONE)
        got = sch.get_work(worker='myworker')['task_params'].get('a', [])
        self.assertEqual(got, ['1', '3', '4'])

    def test_diversity_2(self):
        sch = Scheduler(**{'retry_delay': 100, 'remove_delay': 1000, 'worker_disconnect_delay': 10, 'disable_persist': 10, 'disable_window': 10, 'retry_count': 3, 'disable_hard_timeout': 3600})
        sch.add_task_batcher(worker='myworker', task_family='Azwbtk', batched_args=['a'])
        sch.add_task(worker='myworker', task_id='Azwbtk_a_1', family='Azwbtk', params={'a': '1'}, batchable=True, deps=['DONE_zwbtk'])
        sch.add_task(worker='myworker', task_id='Azwbtk_a_2', family='Azwbtk', params={'a': '2'}, batchable=True, deps=['NOTDONE_zwbtk'])
        sch.add_task(worker='myworker', task_id='Azwbtk_a_3', family='Azwbtk', params={'a': '3'}, batchable=True, deps=['NOTDONE_zwbtk'])
        sch.add_task(worker='myworker', task_id='Azwbtk_a_4', family='Azwbtk', params={'a': '4'}, batchable=True, deps=['NOTDONE_zwbtk'])
        sch.add_task(worker='myworker', task_id='NOTDONE_zwbtk', runnable=False)
        sch.add_task(worker='myworker', task_id='DONE_zwbtk', status=DONE)
        got = sch.get_work(worker='myworker')['task_params'].get('a', [])
        self.assertEqual(got, ['1'])

    def test_diversity_3(self):
        sch = Scheduler(**{'retry_delay': 100, 'remove_delay': 1000, 'worker_disconnect_delay': 10, 'disable_persist': 10, 'disable_window': 10, 'retry_count': 3, 'disable_hard_timeout': 3600})
        sch.add_task_batcher(worker='myworker', task_family='Ajmzszdzcu', batched_args=['a'])
        sch.add_task(worker='myworker', task_id='Ajmzszdzcu_a_1', family='Ajmzszdzcu', params={'a': '1'}, batchable=True, deps=['DONE_jmzszdzcu'])
        sch.add_task(worker='myworker', task_id='Ajmzszdzcu_a_2', family='Ajmzszdzcu', params={'a': '2'}, batchable=True, deps=['NOTDONE_jmzszdzcu'])
        sch.add_task(worker='myworker', task_id='Ajmzszdzcu_a_3', family='Ajmzszdzcu', params={'a': '3'}, batchable=True, deps=['DONE_jmzszdzcu'])
        sch.add_task(worker='myworker', task_id='Ajmzszdzcu_a_4', family='Ajmzszdzcu', params={'a': '4'}, batchable=True, deps=['NOTDONE_jmzszdzcu'])
        sch.add_task(worker='myworker', task_id='Ajmzszdzcu_a_5', family='Ajmzszdzcu', params={'a': '5'}, batchable=True, deps=['DONE_jmzszdzcu'])
        sch.add_task(worker='myworker', task_id='NOTDONE_jmzszdzcu', runnable=False)
        sch.add_task(worker='myworker', task_id='DONE_jmzszdzcu', status=DONE)
        got = sch.get_work(worker='myworker')['task_params'].get('a', [])
        self.assertEqual(got, ['1', '3', '5'])

    def test_diversity_4(self):
        sch = Scheduler(**{'retry_delay': 100, 'remove_delay': 1000, 'worker_disconnect_delay': 10, 'disable_persist': 10, 'disable_window': 10, 'retry_count': 3, 'disable_hard_timeout': 3600})
        sch.add_task_batcher(worker='myworker', task_family='Avuumoik', batched_args=['a'])
        sch.add_task(worker='myworker', task_id='Avuumoik_a_1', family='Avuumoik', params={'a': '1'}, batchable=True, deps=['DONE_vuumoik'])
        sch.add_task(worker='myworker', task_id='Avuumoik_a_2', family='Avuumoik', params={'a': '2'}, batchable=True, deps=['DONE_vuumoik'])
        sch.add_task(worker='myworker', task_id='Avuumoik_a_3', family='Avuumoik', params={'a': '3'}, batchable=True, deps=['DONE_vuumoik'])
        sch.add_task(worker='myworker', task_id='Avuumoik_a_4', family='Avuumoik', params={'a': '4'}, batchable=True, deps=['NOTDONE_vuumoik'])
        sch.add_task(worker='myworker', task_id='Avuumoik_a_5', family='Avuumoik', params={'a': '5'}, batchable=True, deps=['NOTDONE_vuumoik'])
        sch.add_task(worker='myworker', task_id='NOTDONE_vuumoik', runnable=False)
        sch.add_task(worker='myworker', task_id='DONE_vuumoik', status=DONE)
        got = sch.get_work(worker='myworker')['task_params'].get('a', [])
        self.assertEqual(got, ['1', '2', '3'])

    def test_diversity_5(self):
        sch = Scheduler(**{'retry_delay': 100, 'remove_delay': 1000, 'worker_disconnect_delay': 10, 'disable_persist': 10, 'disable_window': 10, 'retry_count': 3, 'disable_hard_timeout': 3600})
        sch.add_task_batcher(worker='myworker', task_family='Akyvpttjn', batched_args=['a'])
        sch.add_task(worker='myworker', task_id='Akyvpttjn_a_1', family='Akyvpttjn', params={'a': '1'}, batchable=True, deps=['DONE_kyvpttjn'])
        sch.add_task(worker='myworker', task_id='Akyvpttjn_a_2', family='Akyvpttjn', params={'a': '2'}, batchable=True, deps=['DONE_kyvpttjn'])
        sch.add_task(worker='myworker', task_id='Akyvpttjn_a_3', family='Akyvpttjn', params={'a': '3'}, batchable=True, deps=['NOTDONE_kyvpttjn'])
        sch.add_task(worker='myworker', task_id='Akyvpttjn_a_4', family='Akyvpttjn', params={'a': '4'}, batchable=True, deps=['NOTDONE_kyvpttjn'])
        sch.add_task(worker='myworker', task_id='Akyvpttjn_a_5', family='Akyvpttjn', params={'a': '5'}, batchable=True, deps=['DONE_kyvpttjn'])
        sch.add_task(worker='myworker', task_id='Akyvpttjn_a_6', family='Akyvpttjn', params={'a': '6'}, batchable=True, deps=['NOTDONE_kyvpttjn'])
        sch.add_task(worker='myworker', task_id='NOTDONE_kyvpttjn', runnable=False)
        sch.add_task(worker='myworker', task_id='DONE_kyvpttjn', status=DONE)
        got = sch.get_work(worker='myworker')['task_params'].get('a', [])
        self.assertEqual(got, ['1', '2', '5'])

    def test_diversity_6(self):
        sch = Scheduler(**{'retry_delay': 100, 'remove_delay': 1000, 'worker_disconnect_delay': 10, 'disable_persist': 10, 'disable_window': 10, 'retry_count': 3, 'disable_hard_timeout': 3600})
        sch.add_task_batcher(worker='myworker', task_family='Ablhyuudu', batched_args=['a'])
        sch.add_task(worker='myworker', task_id='Ablhyuudu_a_1', family='Ablhyuudu', params={'a': '1'}, batchable=True, deps=['DONE_blhyuudu'])
        sch.add_task(worker='myworker', task_id='Ablhyuudu_a_2', family='Ablhyuudu', params={'a': '2'}, batchable=True, deps=['NOTDONE_blhyuudu'])
        sch.add_task(worker='myworker', task_id='Ablhyuudu_a_3', family='Ablhyuudu', params={'a': '3'}, batchable=True, deps=['NOTDONE_blhyuudu'])
        sch.add_task(worker='myworker', task_id='NOTDONE_blhyuudu', runnable=False)
        sch.add_task(worker='myworker', task_id='DONE_blhyuudu', status=DONE)
        got = sch.get_work(worker='myworker')['task_params'].get('a', [])
        self.assertEqual(got, ['1'])

    def test_diversity_7(self):
        sch = Scheduler(**{'retry_delay': 100, 'remove_delay': 1000, 'worker_disconnect_delay': 10, 'disable_persist': 10, 'disable_window': 10, 'retry_count': 3, 'disable_hard_timeout': 3600})
        sch.add_task_batcher(worker='myworker', task_family='Aqstnu', batched_args=['a'])
        sch.add_task(worker='myworker', task_id='Aqstnu_a_1', family='Aqstnu', params={'a': '1'}, batchable=True, deps=['DONE_qstnu'])
        sch.add_task(worker='myworker', task_id='Aqstnu_a_2', family='Aqstnu', params={'a': '2'}, batchable=True, deps=['NOTDONE_qstnu'])
        sch.add_task(worker='myworker', task_id='Aqstnu_a_3', family='Aqstnu', params={'a': '3'}, batchable=True, deps=['DONE_qstnu'])
        sch.add_task(worker='myworker', task_id='Aqstnu_a_4', family='Aqstnu', params={'a': '4'}, batchable=True, deps=['NOTDONE_qstnu'])
        sch.add_task(worker='myworker', task_id='NOTDONE_qstnu', runnable=False)
        sch.add_task(worker='myworker', task_id='DONE_qstnu', status=DONE)
        got = sch.get_work(worker='myworker')['task_params'].get('a', [])
        self.assertEqual(got, ['1', '3'])

    def test_diversity_8(self):
        sch = Scheduler(**{'retry_delay': 100, 'remove_delay': 1000, 'worker_disconnect_delay': 10, 'disable_persist': 10, 'disable_window': 10, 'retry_count': 3, 'disable_hard_timeout': 3600})
        sch.add_task_batcher(worker='myworker', task_family='Agmvxhv', batched_args=['a'])
        sch.add_task(worker='myworker', task_id='Agmvxhv_a_1', family='Agmvxhv', params={'a': '1'}, batchable=True, deps=['DONE_gmvxhv'])
        sch.add_task(worker='myworker', task_id='Agmvxhv_a_2', family='Agmvxhv', params={'a': '2'}, batchable=True, deps=['NOTDONE_gmvxhv'])
        sch.add_task(worker='myworker', task_id='Agmvxhv_a_3', family='Agmvxhv', params={'a': '3'}, batchable=True, deps=['NOTDONE_gmvxhv'])
        sch.add_task(worker='myworker', task_id='Agmvxhv_a_4', family='Agmvxhv', params={'a': '4'}, batchable=True, deps=['NOTDONE_gmvxhv'])
        sch.add_task(worker='myworker', task_id='Agmvxhv_a_5', family='Agmvxhv', params={'a': '5'}, batchable=True, deps=['DONE_gmvxhv'])
        sch.add_task(worker='myworker', task_id='Agmvxhv_a_6', family='Agmvxhv', params={'a': '6'}, batchable=True, deps=['NOTDONE_gmvxhv'])
        sch.add_task(worker='myworker', task_id='NOTDONE_gmvxhv', runnable=False)
        sch.add_task(worker='myworker', task_id='DONE_gmvxhv', status=DONE)
        got = sch.get_work(worker='myworker')['task_params'].get('a', [])
        self.assertEqual(got, ['1', '5'])

    def test_diversity_9(self):
        sch = Scheduler(**{'retry_delay': 100, 'remove_delay': 1000, 'worker_disconnect_delay': 10, 'disable_persist': 10, 'disable_window': 10, 'retry_count': 3, 'disable_hard_timeout': 3600})
        sch.add_task_batcher(worker='myworker', task_family='Amhkqur', batched_args=['a'])
        sch.add_task(worker='myworker', task_id='Amhkqur_a_1', family='Amhkqur', params={'a': '1'}, batchable=True, deps=['DONE_mhkqur'])
        sch.add_task(worker='myworker', task_id='Amhkqur_a_2', family='Amhkqur', params={'a': '2'}, batchable=True, deps=['DONE_mhkqur'])
        sch.add_task(worker='myworker', task_id='Amhkqur_a_3', family='Amhkqur', params={'a': '3'}, batchable=True, deps=['NOTDONE_mhkqur'])
        sch.add_task(worker='myworker', task_id='Amhkqur_a_4', family='Amhkqur', params={'a': '4'}, batchable=True, deps=['NOTDONE_mhkqur'])
        sch.add_task(worker='myworker', task_id='NOTDONE_mhkqur', runnable=False)
        sch.add_task(worker='myworker', task_id='DONE_mhkqur', status=DONE)
        got = sch.get_work(worker='myworker')['task_params'].get('a', [])
        self.assertEqual(got, ['1', '2'])

    def test_diversity_10(self):
        sch = Scheduler(**{'retry_delay': 100, 'remove_delay': 1000, 'worker_disconnect_delay': 10, 'disable_persist': 10, 'disable_window': 10, 'retry_count': 3, 'disable_hard_timeout': 3600})
        sch.add_task_batcher(worker='myworker', task_family='Aqvzfv', batched_args=['a'])
        sch.add_task(worker='myworker', task_id='Aqvzfv_a_1', family='Aqvzfv', params={'a': '1'}, batchable=True, deps=['DONE_qvzfv'])
        sch.add_task(worker='myworker', task_id='Aqvzfv_a_2', family='Aqvzfv', params={'a': '2'}, batchable=True, deps=['NOTDONE_qvzfv'])
        sch.add_task(worker='myworker', task_id='Aqvzfv_a_3', family='Aqvzfv', params={'a': '3'}, batchable=True, deps=['NOTDONE_qvzfv'])
        sch.add_task(worker='myworker', task_id='NOTDONE_qvzfv', runnable=False)
        sch.add_task(worker='myworker', task_id='DONE_qvzfv', status=DONE)
        got = sch.get_work(worker='myworker')['task_params'].get('a', [])
        self.assertEqual(got, ['1'])

class TestsPassing(unittest.TestCase):

    def test_diversity_1(self):
        sch = Scheduler(**{'retry_delay': 100, 'remove_delay': 1000, 'worker_disconnect_delay': 10, 'disable_persist': 10, 'disable_window': 10, 'retry_count': 3, 'disable_hard_timeout': 3600})
        sch.add_task_batcher(worker='myworker', task_family='Awfzcwtrx', batched_args=['a'])
        sch.add_task(worker='myworker', task_id='Awfzcwtrx_a_1', family='Awfzcwtrx', params={'a': '1'}, batchable=True, deps=['DONE_wfzcwtrx'])
        sch.add_task(worker='myworker', task_id='Awfzcwtrx_a_2', family='Awfzcwtrx', params={'a': '2'}, batchable=True, deps=['DONE_wfzcwtrx'])
        sch.add_task(worker='myworker', task_id='Awfzcwtrx_a_3', family='Awfzcwtrx', params={'a': '3'}, batchable=True, deps=['DONE_wfzcwtrx'])
        sch.add_task(worker='myworker', task_id='Awfzcwtrx_a_4', family='Awfzcwtrx', params={'a': '4'}, batchable=True, deps=['DONE_wfzcwtrx'])
        sch.add_task(worker='myworker', task_id='Awfzcwtrx_a_5', family='Awfzcwtrx', params={'a': '5'}, batchable=True, deps=['DONE_wfzcwtrx'])
        sch.add_task(worker='myworker', task_id='NOTDONE_wfzcwtrx', runnable=False)
        sch.add_task(worker='myworker', task_id='DONE_wfzcwtrx', status=DONE)
        got = sch.get_work(worker='myworker')['task_params'].get('a', [])
        self.assertEqual(got, ['1', '2', '3', '4', '5'])

    def test_diversity_2(self):
        sch = Scheduler(**{'retry_delay': 100, 'remove_delay': 1000, 'worker_disconnect_delay': 10, 'disable_persist': 10, 'disable_window': 10, 'retry_count': 3, 'disable_hard_timeout': 3600})
        sch.add_task_batcher(worker='myworker', task_family='Afgymv', batched_args=['a'])
        sch.add_task(worker='myworker', task_id='Afgymv_a_1', family='Afgymv', params={'a': '1'}, batchable=True, deps=['DONE_fgymv'])
        sch.add_task(worker='myworker', task_id='Afgymv_a_2', family='Afgymv', params={'a': '2'}, batchable=True, deps=['DONE_fgymv'])
        sch.add_task(worker='myworker', task_id='Afgymv_a_3', family='Afgymv', params={'a': '3'}, batchable=True, deps=['DONE_fgymv'])
        sch.add_task(worker='myworker', task_id='Afgymv_a_4', family='Afgymv', params={'a': '4'}, batchable=True, deps=['DONE_fgymv'])
        sch.add_task(worker='myworker', task_id='Afgymv_a_5', family='Afgymv', params={'a': '5'}, batchable=True, deps=['DONE_fgymv'])
        sch.add_task(worker='myworker', task_id='Afgymv_a_6', family='Afgymv', params={'a': '6'}, batchable=True, deps=['DONE_fgymv'])
        sch.add_task(worker='myworker', task_id='NOTDONE_fgymv', runnable=False)
        sch.add_task(worker='myworker', task_id='DONE_fgymv', status=DONE)
        got = sch.get_work(worker='myworker')['task_params'].get('a', [])
        self.assertEqual(got, ['1', '2', '3', '4', '5', '6'])

    def test_diversity_3(self):
        sch = Scheduler(**{'retry_delay': 100, 'remove_delay': 1000, 'worker_disconnect_delay': 10, 'disable_persist': 10, 'disable_window': 10, 'retry_count': 3, 'disable_hard_timeout': 3600})
        sch.add_task_batcher(worker='myworker', task_family='Amnkzt', batched_args=['a'])
        sch.add_task(worker='myworker', task_id='Amnkzt_a_1', family='Amnkzt', params={'a': '1'}, batchable=True, deps=['DONE_mnkzt'])
        sch.add_task(worker='myworker', task_id='Amnkzt_a_2', family='Amnkzt', params={'a': '2'}, batchable=True, deps=['DONE_mnkzt'])
        sch.add_task(worker='myworker', task_id='Amnkzt_a_3', family='Amnkzt', params={'a': '3'}, batchable=True, deps=['DONE_mnkzt'])
        sch.add_task(worker='myworker', task_id='Amnkzt_a_4', family='Amnkzt', params={'a': '4'}, batchable=True, deps=['DONE_mnkzt'])
        sch.add_task(worker='myworker', task_id='NOTDONE_mnkzt', runnable=False)
        sch.add_task(worker='myworker', task_id='DONE_mnkzt', status=DONE)
        got = sch.get_work(worker='myworker')['task_params'].get('a', [])
        self.assertEqual(got, ['1', '2', '3', '4'])

    def test_diversity_4(self):
        sch = Scheduler(**{'retry_delay': 100, 'remove_delay': 1000, 'worker_disconnect_delay': 10, 'disable_persist': 10, 'disable_window': 10, 'retry_count': 3, 'disable_hard_timeout': 3600})
        sch.add_task_batcher(worker='myworker', task_family='Akssoc', batched_args=['a'])
        sch.add_task(worker='myworker', task_id='Akssoc_a_1', family='Akssoc', params={'a': '1'}, batchable=True, deps=['DONE_kssoc'])
        sch.add_task(worker='myworker', task_id='Akssoc_a_2', family='Akssoc', params={'a': '2'}, batchable=True, deps=['DONE_kssoc'])
        sch.add_task(worker='myworker', task_id='Akssoc_a_3', family='Akssoc', params={'a': '3'}, batchable=True, deps=['DONE_kssoc'])
        sch.add_task(worker='myworker', task_id='Akssoc_a_4', family='Akssoc', params={'a': '4'}, batchable=True, deps=['DONE_kssoc'])
        sch.add_task(worker='myworker', task_id='NOTDONE_kssoc', runnable=False)
        sch.add_task(worker='myworker', task_id='DONE_kssoc', status=DONE)
        got = sch.get_work(worker='myworker')['task_params'].get('a', [])
        self.assertEqual(got, ['1', '2', '3', '4'])

    def test_diversity_5(self):
        sch = Scheduler(**{'retry_delay': 100, 'remove_delay': 1000, 'worker_disconnect_delay': 10, 'disable_persist': 10, 'disable_window': 10, 'retry_count': 3, 'disable_hard_timeout': 3600})
        sch.add_task_batcher(worker='myworker', task_family='Aeisuc', batched_args=['a'])
        sch.add_task(worker='myworker', task_id='Aeisuc_a_1', family='Aeisuc', params={'a': '1'}, batchable=True, deps=['DONE_eisuc'])
        sch.add_task(worker='myworker', task_id='Aeisuc_a_2', family='Aeisuc', params={'a': '2'}, batchable=True, deps=['DONE_eisuc'])
        sch.add_task(worker='myworker', task_id='Aeisuc_a_3', family='Aeisuc', params={'a': '3'}, batchable=True, deps=['DONE_eisuc'])
        sch.add_task(worker='myworker', task_id='Aeisuc_a_4', family='Aeisuc', params={'a': '4'}, batchable=True, deps=['DONE_eisuc'])
        sch.add_task(worker='myworker', task_id='NOTDONE_eisuc', runnable=False)
        sch.add_task(worker='myworker', task_id='DONE_eisuc', status=DONE)
        got = sch.get_work(worker='myworker')['task_params'].get('a', [])
        self.assertEqual(got, ['1', '2', '3', '4'])

    def test_diversity_6(self):
        sch = Scheduler(**{'retry_delay': 100, 'remove_delay': 1000, 'worker_disconnect_delay': 10, 'disable_persist': 10, 'disable_window': 10, 'retry_count': 3, 'disable_hard_timeout': 3600})
        sch.add_task_batcher(worker='myworker', task_family='Aktqa', batched_args=['a'])
        sch.add_task(worker='myworker', task_id='Aktqa_a_1', family='Aktqa', params={'a': '1'}, batchable=True, deps=['DONE_ktqa'])
        sch.add_task(worker='myworker', task_id='Aktqa_a_2', family='Aktqa', params={'a': '2'}, batchable=True, deps=['DONE_ktqa'])
        sch.add_task(worker='myworker', task_id='Aktqa_a_3', family='Aktqa', params={'a': '3'}, batchable=True, deps=['DONE_ktqa'])
        sch.add_task(worker='myworker', task_id='Aktqa_a_4', family='Aktqa', params={'a': '4'}, batchable=True, deps=['DONE_ktqa'])
        sch.add_task(worker='myworker', task_id='Aktqa_a_5', family='Aktqa', params={'a': '5'}, batchable=True, deps=['DONE_ktqa'])
        sch.add_task(worker='myworker', task_id='Aktqa_a_6', family='Aktqa', params={'a': '6'}, batchable=True, deps=['DONE_ktqa'])
        sch.add_task(worker='myworker', task_id='NOTDONE_ktqa', runnable=False)
        sch.add_task(worker='myworker', task_id='DONE_ktqa', status=DONE)
        got = sch.get_work(worker='myworker')['task_params'].get('a', [])
        self.assertEqual(got, ['1', '2', '3', '4', '5', '6'])

    def test_diversity_7(self):
        sch = Scheduler(**{'retry_delay': 100, 'remove_delay': 1000, 'worker_disconnect_delay': 10, 'disable_persist': 10, 'disable_window': 10, 'retry_count': 3, 'disable_hard_timeout': 3600})
        sch.add_task_batcher(worker='myworker', task_family='Amvcqbqgv', batched_args=['a'])
        sch.add_task(worker='myworker', task_id='Amvcqbqgv_a_1', family='Amvcqbqgv', params={'a': '1'}, batchable=True, deps=['DONE_mvcqbqgv'])
        sch.add_task(worker='myworker', task_id='Amvcqbqgv_a_2', family='Amvcqbqgv', params={'a': '2'}, batchable=True, deps=['DONE_mvcqbqgv'])
        sch.add_task(worker='myworker', task_id='Amvcqbqgv_a_3', family='Amvcqbqgv', params={'a': '3'}, batchable=True, deps=['DONE_mvcqbqgv'])
        sch.add_task(worker='myworker', task_id='Amvcqbqgv_a_4', family='Amvcqbqgv', params={'a': '4'}, batchable=True, deps=['DONE_mvcqbqgv'])
        sch.add_task(worker='myworker', task_id='Amvcqbqgv_a_5', family='Amvcqbqgv', params={'a': '5'}, batchable=True, deps=['DONE_mvcqbqgv'])
        sch.add_task(worker='myworker', task_id='NOTDONE_mvcqbqgv', runnable=False)
        sch.add_task(worker='myworker', task_id='DONE_mvcqbqgv', status=DONE)
        got = sch.get_work(worker='myworker')['task_params'].get('a', [])
        self.assertEqual(got, ['1', '2', '3', '4', '5'])

    def test_diversity_8(self):
        sch = Scheduler(**{'retry_delay': 100, 'remove_delay': 1000, 'worker_disconnect_delay': 10, 'disable_persist': 10, 'disable_window': 10, 'retry_count': 3, 'disable_hard_timeout': 3600})
        sch.add_task_batcher(worker='myworker', task_family='Algng', batched_args=['a'])
        sch.add_task(worker='myworker', task_id='Algng_a_1', family='Algng', params={'a': '1'}, batchable=True, deps=['DONE_lgng'])
        sch.add_task(worker='myworker', task_id='Algng_a_2', family='Algng', params={'a': '2'}, batchable=True, deps=['DONE_lgng'])
        sch.add_task(worker='myworker', task_id='Algng_a_3', family='Algng', params={'a': '3'}, batchable=True, deps=['DONE_lgng'])
        sch.add_task(worker='myworker', task_id='NOTDONE_lgng', runnable=False)
        sch.add_task(worker='myworker', task_id='DONE_lgng', status=DONE)
        got = sch.get_work(worker='myworker')['task_params'].get('a', [])
        self.assertEqual(got, ['1', '2', '3'])

    def test_diversity_9(self):
        sch = Scheduler(**{'retry_delay': 100, 'remove_delay': 1000, 'worker_disconnect_delay': 10, 'disable_persist': 10, 'disable_window': 10, 'retry_count': 3, 'disable_hard_timeout': 3600})
        sch.add_task_batcher(worker='myworker', task_family='Aaxnxocd', batched_args=['a'])
        sch.add_task(worker='myworker', task_id='Aaxnxocd_a_1', family='Aaxnxocd', params={'a': '1'}, batchable=True, deps=['DONE_axnxocd'])
        sch.add_task(worker='myworker', task_id='Aaxnxocd_a_2', family='Aaxnxocd', params={'a': '2'}, batchable=True, deps=['DONE_axnxocd'])
        sch.add_task(worker='myworker', task_id='Aaxnxocd_a_3', family='Aaxnxocd', params={'a': '3'}, batchable=True, deps=['DONE_axnxocd'])
        sch.add_task(worker='myworker', task_id='Aaxnxocd_a_4', family='Aaxnxocd', params={'a': '4'}, batchable=True, deps=['DONE_axnxocd'])
        sch.add_task(worker='myworker', task_id='Aaxnxocd_a_5', family='Aaxnxocd', params={'a': '5'}, batchable=True, deps=['DONE_axnxocd'])
        sch.add_task(worker='myworker', task_id='Aaxnxocd_a_6', family='Aaxnxocd', params={'a': '6'}, batchable=True, deps=['DONE_axnxocd'])
        sch.add_task(worker='myworker', task_id='NOTDONE_axnxocd', runnable=False)
        sch.add_task(worker='myworker', task_id='DONE_axnxocd', status=DONE)
        got = sch.get_work(worker='myworker')['task_params'].get('a', [])
        self.assertEqual(got, ['1', '2', '3', '4', '5', '6'])

    def test_diversity_10(self):
        sch = Scheduler(**{'retry_delay': 100, 'remove_delay': 1000, 'worker_disconnect_delay': 10, 'disable_persist': 10, 'disable_window': 10, 'retry_count': 3, 'disable_hard_timeout': 3600})
        sch.add_task_batcher(worker='myworker', task_family='Atunmknni', batched_args=['a'])
        sch.add_task(worker='myworker', task_id='Atunmknni_a_1', family='Atunmknni', params={'a': '1'}, batchable=True, deps=['DONE_tunmknni'])
        sch.add_task(worker='myworker', task_id='Atunmknni_a_2', family='Atunmknni', params={'a': '2'}, batchable=True, deps=['DONE_tunmknni'])
        sch.add_task(worker='myworker', task_id='Atunmknni_a_3', family='Atunmknni', params={'a': '3'}, batchable=True, deps=['DONE_tunmknni'])
        sch.add_task(worker='myworker', task_id='Atunmknni_a_4', family='Atunmknni', params={'a': '4'}, batchable=True, deps=['DONE_tunmknni'])
        sch.add_task(worker='myworker', task_id='NOTDONE_tunmknni', runnable=False)
        sch.add_task(worker='myworker', task_id='DONE_tunmknni', status=DONE)
        got = sch.get_work(worker='myworker')['task_params'].get('a', [])
        self.assertEqual(got, ['1', '2', '3', '4'])
