import unittest
from io import BytesIO
import matplotlib
matplotlib.use('Agg')
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

class TestsFailing(unittest.TestCase):

    def test_diversity_1(self):
        fig = plt.figure(frameon=False, dpi=100, figsize=(14 / 100, 7 / 100))
        ax = plt.Axes(fig, [0.0, 0.0, 1.0, 1.0])
        fig.add_axes(ax)
        ax.set_axis_off()
        ax.get_xaxis().set_visible(False)
        ax.get_yaxis().set_visible(False)
        data = np.arange(14 * 7).reshape(7, 14)
        ax.imshow(data)
        out = BytesIO()
        fig.savefig(out, bbox_inches='tight', pad_inches=0)
        out.seek(0)
        im = np.asarray(Image.open(out))
        ok = bool((im[:, :, 3] == 255).all() and (not (im[:, :, :3] == 255).all()))
        self.assertEqual(True, ok)
        plt.close(fig)

    def test_diversity_2(self):
        fig = plt.figure(frameon=False, dpi=100, figsize=(29 / 100, 7 / 100))
        ax = plt.Axes(fig, [0.0, 0.0, 1.0, 1.0])
        fig.add_axes(ax)
        ax.set_axis_off()
        ax.get_xaxis().set_visible(False)
        ax.get_yaxis().set_visible(False)
        data = np.arange(29 * 7).reshape(7, 29)
        ax.imshow(data)
        out = BytesIO()
        fig.savefig(out, bbox_inches='tight', pad_inches=0)
        out.seek(0)
        im = np.asarray(Image.open(out))
        ok = bool((im[:, :, 3] == 255).all() and (not (im[:, :, :3] == 255).all()))
        self.assertEqual(True, ok)
        plt.close(fig)

    def test_diversity_3(self):
        fig = plt.figure(frameon=False, dpi=100, figsize=(25 / 100, 7 / 100))
        ax = plt.Axes(fig, [0.0, 0.0, 1.0, 1.0])
        fig.add_axes(ax)
        ax.set_axis_off()
        ax.get_xaxis().set_visible(False)
        ax.get_yaxis().set_visible(False)
        data = np.arange(25 * 7).reshape(7, 25)
        ax.imshow(data)
        out = BytesIO()
        fig.savefig(out, bbox_inches='tight', pad_inches=0)
        out.seek(0)
        im = np.asarray(Image.open(out))
        ok = bool((im[:, :, 3] == 255).all() and (not (im[:, :, :3] == 255).all()))
        self.assertEqual(True, ok)
        plt.close(fig)

    def test_diversity_4(self):
        fig = plt.figure(frameon=False, dpi=100, figsize=(16 / 100, 7 / 100))
        ax = plt.Axes(fig, [0.0, 0.0, 1.0, 1.0])
        fig.add_axes(ax)
        ax.set_axis_off()
        ax.get_xaxis().set_visible(False)
        ax.get_yaxis().set_visible(False)
        data = np.arange(16 * 7).reshape(7, 16)
        ax.imshow(data)
        out = BytesIO()
        fig.savefig(out, bbox_inches='tight', pad_inches=0)
        out.seek(0)
        im = np.asarray(Image.open(out))
        ok = bool((im[:, :, 3] == 255).all() and (not (im[:, :, :3] == 255).all()))
        self.assertEqual(True, ok)
        plt.close(fig)

    def test_diversity_5(self):
        fig = plt.figure(frameon=False, dpi=100, figsize=(30 / 100, 7 / 100))
        ax = plt.Axes(fig, [0.0, 0.0, 1.0, 1.0])
        fig.add_axes(ax)
        ax.set_axis_off()
        ax.get_xaxis().set_visible(False)
        ax.get_yaxis().set_visible(False)
        data = np.arange(30 * 7).reshape(7, 30)
        ax.imshow(data)
        out = BytesIO()
        fig.savefig(out, bbox_inches='tight', pad_inches=0)
        out.seek(0)
        im = np.asarray(Image.open(out))
        ok = bool((im[:, :, 3] == 255).all() and (not (im[:, :, :3] == 255).all()))
        self.assertEqual(True, ok)
        plt.close(fig)

    def test_diversity_6(self):
        fig = plt.figure(frameon=False, dpi=100, figsize=(9 / 100, 7 / 100))
        ax = plt.Axes(fig, [0.0, 0.0, 1.0, 1.0])
        fig.add_axes(ax)
        ax.set_axis_off()
        ax.get_xaxis().set_visible(False)
        ax.get_yaxis().set_visible(False)
        data = np.arange(9 * 7).reshape(7, 9)
        ax.imshow(data)
        out = BytesIO()
        fig.savefig(out, bbox_inches='tight', pad_inches=0)
        out.seek(0)
        im = np.asarray(Image.open(out))
        ok = bool((im[:, :, 3] == 255).all() and (not (im[:, :, :3] == 255).all()))
        self.assertEqual(True, ok)
        plt.close(fig)

    def test_diversity_7(self):
        fig = plt.figure(frameon=False, dpi=100, figsize=(21 / 100, 7 / 100))
        ax = plt.Axes(fig, [0.0, 0.0, 1.0, 1.0])
        fig.add_axes(ax)
        ax.set_axis_off()
        ax.get_xaxis().set_visible(False)
        ax.get_yaxis().set_visible(False)
        data = np.arange(21 * 7).reshape(7, 21)
        ax.imshow(data)
        out = BytesIO()
        fig.savefig(out, bbox_inches='tight', pad_inches=0)
        out.seek(0)
        im = np.asarray(Image.open(out))
        ok = bool((im[:, :, 3] == 255).all() and (not (im[:, :, :3] == 255).all()))
        self.assertEqual(True, ok)
        plt.close(fig)

    def test_diversity_8(self):
        fig = plt.figure(frameon=False, dpi=100, figsize=(24 / 100, 7 / 100))
        ax = plt.Axes(fig, [0.0, 0.0, 1.0, 1.0])
        fig.add_axes(ax)
        ax.set_axis_off()
        ax.get_xaxis().set_visible(False)
        ax.get_yaxis().set_visible(False)
        data = np.arange(24 * 7).reshape(7, 24)
        ax.imshow(data)
        out = BytesIO()
        fig.savefig(out, bbox_inches='tight', pad_inches=0)
        out.seek(0)
        im = np.asarray(Image.open(out))
        ok = bool((im[:, :, 3] == 255).all() and (not (im[:, :, :3] == 255).all()))
        self.assertEqual(True, ok)
        plt.close(fig)

    def test_diversity_9(self):
        fig = plt.figure(frameon=False, dpi=100, figsize=(15 / 100, 7 / 100))
        ax = plt.Axes(fig, [0.0, 0.0, 1.0, 1.0])
        fig.add_axes(ax)
        ax.set_axis_off()
        ax.get_xaxis().set_visible(False)
        ax.get_yaxis().set_visible(False)
        data = np.arange(15 * 7).reshape(7, 15)
        ax.imshow(data)
        out = BytesIO()
        fig.savefig(out, bbox_inches='tight', pad_inches=0)
        out.seek(0)
        im = np.asarray(Image.open(out))
        ok = bool((im[:, :, 3] == 255).all() and (not (im[:, :, :3] == 255).all()))
        self.assertEqual(True, ok)
        plt.close(fig)

    def test_diversity_10(self):
        fig = plt.figure(frameon=False, dpi=100, figsize=(12 / 100, 7 / 100))
        ax = plt.Axes(fig, [0.0, 0.0, 1.0, 1.0])
        fig.add_axes(ax)
        ax.set_axis_off()
        ax.get_xaxis().set_visible(False)
        ax.get_yaxis().set_visible(False)
        data = np.arange(12 * 7).reshape(7, 12)
        ax.imshow(data)
        out = BytesIO()
        fig.savefig(out, bbox_inches='tight', pad_inches=0)
        out.seek(0)
        im = np.asarray(Image.open(out))
        ok = bool((im[:, :, 3] == 255).all() and (not (im[:, :, :3] == 255).all()))
        self.assertEqual(True, ok)
        plt.close(fig)

class TestsPassing(unittest.TestCase):

    def test_diversity_1(self):
        fig = plt.figure(frameon=False, dpi=100, figsize=(28 / 100, 16 / 100))
        ax = plt.Axes(fig, [0.0, 0.0, 1.0, 1.0])
        fig.add_axes(ax)
        ax.set_axis_off()
        ax.get_xaxis().set_visible(False)
        ax.get_yaxis().set_visible(False)
        data = np.arange(28 * 16).reshape(16, 28)
        ax.imshow(data)
        out = BytesIO()
        fig.savefig(out)
        out.seek(0)
        im = np.asarray(Image.open(out))
        ok = bool((im[:, :, 3] == 255).all() and (not (im[:, :, :3] == 255).all()))
        self.assertEqual(True, ok)
        plt.close(fig)

    def test_diversity_2(self):
        fig = plt.figure(frameon=False, dpi=100, figsize=(7 / 100, 7 / 100))
        ax = plt.Axes(fig, [0.0, 0.0, 1.0, 1.0])
        fig.add_axes(ax)
        ax.set_axis_off()
        ax.get_xaxis().set_visible(False)
        ax.get_yaxis().set_visible(False)
        data = np.arange(7 * 7).reshape(7, 7)
        ax.imshow(data)
        out = BytesIO()
        fig.savefig(out)
        out.seek(0)
        im = np.asarray(Image.open(out))
        ok = bool((im[:, :, 3] == 255).all() and (not (im[:, :, :3] == 255).all()))
        self.assertEqual(True, ok)
        plt.close(fig)

    def test_diversity_3(self):
        fig = plt.figure(frameon=False, dpi=150, figsize=(22 / 150, 16 / 150))
        ax = plt.Axes(fig, [0.0, 0.0, 1.0, 1.0])
        fig.add_axes(ax)
        ax.set_axis_off()
        ax.get_xaxis().set_visible(False)
        ax.get_yaxis().set_visible(False)
        data = np.arange(22 * 16).reshape(16, 22)
        ax.imshow(data)
        out = BytesIO()
        fig.savefig(out)
        out.seek(0)
        im = np.asarray(Image.open(out))
        ok = bool((im[:, :, 3] == 255).all() and (not (im[:, :, :3] == 255).all()))
        self.assertEqual(True, ok)
        plt.close(fig)

    def test_diversity_4(self):
        fig = plt.figure(frameon=False, dpi=80, figsize=(6 / 80, 19 / 80))
        ax = plt.Axes(fig, [0.0, 0.0, 1.0, 1.0])
        fig.add_axes(ax)
        ax.set_axis_off()
        ax.get_xaxis().set_visible(False)
        ax.get_yaxis().set_visible(False)
        data = np.arange(6 * 19).reshape(19, 6)
        ax.imshow(data)
        out = BytesIO()
        fig.savefig(out)
        out.seek(0)
        im = np.asarray(Image.open(out))
        ok = bool((im[:, :, 3] == 255).all() and (not (im[:, :, :3] == 255).all()))
        self.assertEqual(True, ok)
        plt.close(fig)

    def test_diversity_5(self):
        fig = plt.figure(frameon=False, dpi=100, figsize=(26 / 100, 9 / 100))
        ax = plt.Axes(fig, [0.0, 0.0, 1.0, 1.0])
        fig.add_axes(ax)
        ax.set_axis_off()
        ax.get_xaxis().set_visible(False)
        ax.get_yaxis().set_visible(False)
        data = np.arange(26 * 9).reshape(9, 26)
        ax.imshow(data)
        out = BytesIO()
        fig.savefig(out)
        out.seek(0)
        im = np.asarray(Image.open(out))
        ok = bool((im[:, :, 3] == 255).all() and (not (im[:, :, :3] == 255).all()))
        self.assertEqual(True, ok)
        plt.close(fig)

    def test_diversity_6(self):
        fig = plt.figure(frameon=False, dpi=120, figsize=(9 / 120, 20 / 120))
        ax = plt.Axes(fig, [0.0, 0.0, 1.0, 1.0])
        fig.add_axes(ax)
        ax.set_axis_off()
        ax.get_xaxis().set_visible(False)
        ax.get_yaxis().set_visible(False)
        data = np.arange(9 * 20).reshape(20, 9)
        ax.imshow(data)
        out = BytesIO()
        fig.savefig(out)
        out.seek(0)
        im = np.asarray(Image.open(out))
        ok = bool((im[:, :, 3] == 255).all() and (not (im[:, :, :3] == 255).all()))
        self.assertEqual(True, ok)
        plt.close(fig)

    def test_diversity_7(self):
        fig = plt.figure(frameon=False, dpi=80, figsize=(14 / 80, 8 / 80))
        ax = plt.Axes(fig, [0.0, 0.0, 1.0, 1.0])
        fig.add_axes(ax)
        ax.set_axis_off()
        ax.get_xaxis().set_visible(False)
        ax.get_yaxis().set_visible(False)
        data = np.arange(14 * 8).reshape(8, 14)
        ax.imshow(data)
        out = BytesIO()
        fig.savefig(out)
        out.seek(0)
        im = np.asarray(Image.open(out))
        ok = bool((im[:, :, 3] == 255).all() and (not (im[:, :, :3] == 255).all()))
        self.assertEqual(True, ok)
        plt.close(fig)

    def test_diversity_8(self):
        fig = plt.figure(frameon=False, dpi=150, figsize=(13 / 150, 8 / 150))
        ax = plt.Axes(fig, [0.0, 0.0, 1.0, 1.0])
        fig.add_axes(ax)
        ax.set_axis_off()
        ax.get_xaxis().set_visible(False)
        ax.get_yaxis().set_visible(False)
        data = np.arange(13 * 8).reshape(8, 13)
        ax.imshow(data)
        out = BytesIO()
        fig.savefig(out)
        out.seek(0)
        im = np.asarray(Image.open(out))
        ok = bool((im[:, :, 3] == 255).all() and (not (im[:, :, :3] == 255).all()))
        self.assertEqual(True, ok)
        plt.close(fig)

    def test_diversity_9(self):
        fig = plt.figure(frameon=False, dpi=80, figsize=(12 / 80, 16 / 80))
        ax = plt.Axes(fig, [0.0, 0.0, 1.0, 1.0])
        fig.add_axes(ax)
        ax.set_axis_off()
        ax.get_xaxis().set_visible(False)
        ax.get_yaxis().set_visible(False)
        data = np.arange(12 * 16).reshape(16, 12)
        ax.imshow(data)
        out = BytesIO()
        fig.savefig(out)
        out.seek(0)
        im = np.asarray(Image.open(out))
        ok = bool((im[:, :, 3] == 255).all() and (not (im[:, :, :3] == 255).all()))
        self.assertEqual(True, ok)
        plt.close(fig)

    def test_diversity_10(self):
        fig = plt.figure(frameon=False, dpi=120, figsize=(8 / 120, 15 / 120))
        ax = plt.Axes(fig, [0.0, 0.0, 1.0, 1.0])
        fig.add_axes(ax)
        ax.set_axis_off()
        ax.get_xaxis().set_visible(False)
        ax.get_yaxis().set_visible(False)
        data = np.arange(8 * 15).reshape(15, 8)
        ax.imshow(data)
        out = BytesIO()
        fig.savefig(out)
        out.seek(0)
        im = np.asarray(Image.open(out))
        ok = bool((im[:, :, 3] == 255).all() and (not (im[:, :, :3] == 255).all()))
        self.assertEqual(True, ok)
        plt.close(fig)
