from tests4py.tests.diversity import FailingSystemtests, PassingSystemtests


class TestsFailing(FailingSystemtests):
    def test_diversity_1(self):
        return '\n        1\t[\tPUNCT\t-\t-LRB-\t_\t_\tpunct\t_\t_\n        2\tThis\t_\tDET\tDT\t_\t_\tdet\t_\t_\n        3\tfrfussr\t_\tNOUN\tNN\t_\t_\tnsubj\t_\t_\n        4\tof\t_\tADP\tIN\t_\t_\tcase\t_\t_\n        5\ta\t_\tDET\tDT\t_\t_\tdet\t_\t_\n        6\trespected\t_\tADJ\tJJ\t_\t_\tamod\t_\t_\n        7\tcleric\t_\tNOUN\tNN\t_\t_\tnmod\t_\t_\n        8\twill\t_\tAUX\tMD\t_\t_\taux\t_\t_\n        9\tbe\t_\tAUX\tVB\t_\t_\taux\t_\t_\n        10\tcausing\t_\tVERB\tVBG\t_\t_\troot\t_\t_\n        11\tus\t_\tPRON\tPRP\t_\t_\tiobj\t_\t_\n        12\thjjsdjcs\t_\tNOUN\tNN\t_\t_\tdobj\t_\t_\n        13\tfor\t_\tADP\tIN\t_\t_\tcase\t_\t_\n        14\tyears\t_\tNOUN\tNNS\t_\t_\tnmod\t_\t_\n        15\tto\t_\tPART\tTO\t_\t_\tmark\t_\t_\n        16\tcome\t_\tVERB\tVB\t_\t_\tacl\t_\t_\n        17\t.\t_\tPUNCT\t.\t_\t_\tpunct\t_\t_\n        18\t]\t_\tPUNCT\t-RRB-\t_\t_\tpunct\t_\t_\n        '

    def test_diversity_2(self):
        return '\n        1\t[\tPUNCT\t-\t-LRB-\t_\t_\tpunct\t_\t_\n        2\tThis\t_\tDET\tDT\t_\t_\tdet\t_\t_\n        3\thfbshf\t_\tNOUN\tNN\t_\t_\tnsubj\t_\t_\n        4\tof\t_\tADP\tIN\t_\t_\tcase\t_\t_\n        5\ta\t_\tDET\tDT\t_\t_\tdet\t_\t_\n        6\trespected\t_\tADJ\tJJ\t_\t_\tamod\t_\t_\n        7\tcleric\t_\tNOUN\tNN\t_\t_\tnmod\t_\t_\n        8\twill\t_\tAUX\tMD\t_\t_\taux\t_\t_\n        9\tbe\t_\tAUX\tVB\t_\t_\taux\t_\t_\n        10\tcausing\t_\tVERB\tVBG\t_\t_\troot\t_\t_\n        11\tus\t_\tPRON\tPRP\t_\t_\tiobj\t_\t_\n        12\thbfwehufw\t_\tNOUN\tNN\t_\t_\tdobj\t_\t_\n        13\tfor\t_\tADP\tIN\t_\t_\tcase\t_\t_\n        14\tyears\t_\tNOUN\tNNS\t_\t_\tnmod\t_\t_\n        15\tto\t_\tPART\tTO\t_\t_\tmark\t_\t_\n        16\tcome\t_\tVERB\tVB\t_\t_\tacl\t_\t_\n        17\t.\t_\tPUNCT\t.\t_\t_\tpunct\t_\t_\n        18\t]\t_\tPUNCT\t-RRB-\t_\t_\tpunct\t_\t_\n        '

    def test_diversity_3(self):
        return '\n        1\t[\tPUNCT\t-\t-LRB-\t_\t_\tpunct\t_\t_\n        2\tThis\t_\tDET\tDT\t_\t_\tdet\t_\t_\n        3\thjrfbuw\t_\tNOUN\tNN\t_\t_\tnsubj\t_\t_\n        4\tof\t_\tADP\tIN\t_\t_\tcase\t_\t_\n        5\ta\t_\tDET\tDT\t_\t_\tdet\t_\t_\n        6\trespected\t_\tADJ\tJJ\t_\t_\tamod\t_\t_\n        7\tcleric\t_\tNOUN\tNN\t_\t_\tnmod\t_\t_\n        8\twill\t_\tAUX\tMD\t_\t_\taux\t_\t_\n        9\tbe\t_\tAUX\tVB\t_\t_\taux\t_\t_\n        10\tcausing\t_\tVERB\tVBG\t_\t_\troot\t_\t_\n        11\tus\t_\tPRON\tPRP\t_\t_\tiobj\t_\t_\n        12\tjwefbugew\t_\tNOUN\tNN\t_\t_\tdobj\t_\t_\n        13\tfor\t_\tADP\tIN\t_\t_\tcase\t_\t_\n        14\tyears\t_\tNOUN\tNNS\t_\t_\tnmod\t_\t_\n        15\tto\t_\tPART\tTO\t_\t_\tmark\t_\t_\n        16\tcome\t_\tVERB\tVB\t_\t_\tacl\t_\t_\n        17\t.\t_\tPUNCT\t.\t_\t_\tpunct\t_\t_\n        18\t]\t_\tPUNCT\t-RRB-\t_\t_\tpunct\t_\t_\n        '

    def test_diversity_4(self):
        return '\n        1\t[\tPUNCT\t-\t-LRB-\t_\t_\tpunct\t_\t_\n        2\tThis\t_\tDET\tDT\t_\t_\tdet\t_\t_\n        3\tjerfhige\t_\tNOUN\tNN\t_\t_\tnsubj\t_\t_\n        4\tof\t_\tADP\tIN\t_\t_\tcase\t_\t_\n        5\ta\t_\tDET\tDT\t_\t_\tdet\t_\t_\n        6\trespected\t_\tADJ\tJJ\t_\t_\tamod\t_\t_\n        7\tcleric\t_\tNOUN\tNN\t_\t_\tnmod\t_\t_\n        8\twill\t_\tAUX\tMD\t_\t_\taux\t_\t_\n        9\tbe\t_\tAUX\tVB\t_\t_\taux\t_\t_\n        10\tcausing\t_\tVERB\tVBG\t_\t_\troot\t_\t_\n        11\tus\t_\tPRON\tPRP\t_\t_\tiobj\t_\t_\n        12\tgvwegdf\t_\tNOUN\tNN\t_\t_\tdobj\t_\t_\n        13\tfor\t_\tADP\tIN\t_\t_\tcase\t_\t_\n        14\tyears\t_\tNOUN\tNNS\t_\t_\tnmod\t_\t_\n        15\tto\t_\tPART\tTO\t_\t_\tmark\t_\t_\n        16\tcome\t_\tVERB\tVB\t_\t_\tacl\t_\t_\n        17\t.\t_\tPUNCT\t.\t_\t_\tpunct\t_\t_\n        18\t]\t_\tPUNCT\t-RRB-\t_\t_\tpunct\t_\t_\n        '

    def test_diversity_5(self):
        return '\n        1\t[\tPUNCT\t-\t-LRB-\t_\t_\tpunct\t_\t_\n        2\tThis\t_\tDET\tDT\t_\t_\tdet\t_\t_\n        3\tgewfe\t_\tNOUN\tNN\t_\t_\tnsubj\t_\t_\n        4\tof\t_\tADP\tIN\t_\t_\tcase\t_\t_\n        5\ta\t_\tDET\tDT\t_\t_\tdet\t_\t_\n        6\trespected\t_\tADJ\tJJ\t_\t_\tamod\t_\t_\n        7\tcleric\t_\tNOUN\tNN\t_\t_\tnmod\t_\t_\n        8\twill\t_\tAUX\tMD\t_\t_\taux\t_\t_\n        9\tbe\t_\tAUX\tVB\t_\t_\taux\t_\t_\n        10\tcausing\t_\tVERB\tVBG\t_\t_\troot\t_\t_\n        11\tus\t_\tPRON\tPRP\t_\t_\tiobj\t_\t_\n        12\tfjherbhf\t_\tNOUN\tNN\t_\t_\tdobj\t_\t_\n        13\tfor\t_\tADP\tIN\t_\t_\tcase\t_\t_\n        14\tyears\t_\tNOUN\tNNS\t_\t_\tnmod\t_\t_\n        15\tto\t_\tPART\tTO\t_\t_\tmark\t_\t_\n        16\tcome\t_\tVERB\tVB\t_\t_\tacl\t_\t_\n        17\t.\t_\tPUNCT\t.\t_\t_\tpunct\t_\t_\n        18\t]\t_\tPUNCT\t-RRB-\t_\t_\tpunct\t_\t_\n        '

    def test_diversity_6(self):
        return '\n        1\t[\tPUNCT\t-\t-LRB-\t_\t_\tpunct\t_\t_\n        2\tThis\t_\tDET\tDT\t_\t_\tdet\t_\t_\n        3\tjhwefuw\t_\tNOUN\tNN\t_\t_\tnsubj\t_\t_\n        4\tof\t_\tADP\tIN\t_\t_\tcase\t_\t_\n        5\ta\t_\tDET\tDT\t_\t_\tdet\t_\t_\n        6\trespected\t_\tADJ\tJJ\t_\t_\tamod\t_\t_\n        7\tcleric\t_\tNOUN\tNN\t_\t_\tnmod\t_\t_\n        8\twill\t_\tAUX\tMD\t_\t_\taux\t_\t_\n        9\tbe\t_\tAUX\tVB\t_\t_\taux\t_\t_\n        10\tcausing\t_\tVERB\tVBG\t_\t_\troot\t_\t_\n        11\tus\t_\tPRON\tPRP\t_\t_\tiobj\t_\t_\n        12\thbjfwe\t_\tNOUN\tNN\t_\t_\tdobj\t_\t_\n        13\tfor\t_\tADP\tIN\t_\t_\tcase\t_\t_\n        14\tyears\t_\tNOUN\tNNS\t_\t_\tnmod\t_\t_\n        15\tto\t_\tPART\tTO\t_\t_\tmark\t_\t_\n        16\tcome\t_\tVERB\tVB\t_\t_\tacl\t_\t_\n        17\t.\t_\tPUNCT\t.\t_\t_\tpunct\t_\t_\n        18\t]\t_\tPUNCT\t-RRB-\t_\t_\tpunct\t_\t_\n        '

    def test_diversity_7(self):
        return '\n        1\t[\tPUNCT\t-\t-LRB-\t_\t_\tpunct\t_\t_\n        2\tThis\t_\tDET\tDT\t_\t_\tdet\t_\t_\n        3\twehjfjew\t_\tNOUN\tNN\t_\t_\tnsubj\t_\t_\n        4\tof\t_\tADP\tIN\t_\t_\tcase\t_\t_\n        5\ta\t_\tDET\tDT\t_\t_\tdet\t_\t_\n        6\trespected\t_\tADJ\tJJ\t_\t_\tamod\t_\t_\n        7\tcleric\t_\tNOUN\tNN\t_\t_\tnmod\t_\t_\n        8\twill\t_\tAUX\tMD\t_\t_\taux\t_\t_\n        9\tbe\t_\tAUX\tVB\t_\t_\taux\t_\t_\n        10\tcausing\t_\tVERB\tVBG\t_\t_\troot\t_\t_\n        11\tus\t_\tPRON\tPRP\t_\t_\tiobj\t_\t_\n        12\thjrwbfj\t_\tNOUN\tNN\t_\t_\tdobj\t_\t_\n        13\tfor\t_\tADP\tIN\t_\t_\tcase\t_\t_\n        14\tyears\t_\tNOUN\tNNS\t_\t_\tnmod\t_\t_\n        15\tto\t_\tPART\tTO\t_\t_\tmark\t_\t_\n        16\tcome\t_\tVERB\tVB\t_\t_\tacl\t_\t_\n        17\t.\t_\tPUNCT\t.\t_\t_\tpunct\t_\t_\n        18\t]\t_\tPUNCT\t-RRB-\t_\t_\tpunct\t_\t_\n        '

    def test_diversity_8(self):
        return '\n        1\t[\tPUNCT\t-\t-LRB-\t_\t_\tpunct\t_\t_\n        2\tThis\t_\tDET\tDT\t_\t_\tdet\t_\t_\n        3\twefjw\t_\tNOUN\tNN\t_\t_\tnsubj\t_\t_\n        4\tof\t_\tADP\tIN\t_\t_\tcase\t_\t_\n        5\ta\t_\tDET\tDT\t_\t_\tdet\t_\t_\n        6\trespected\t_\tADJ\tJJ\t_\t_\tamod\t_\t_\n        7\tcleric\t_\tNOUN\tNN\t_\t_\tnmod\t_\t_\n        8\twill\t_\tAUX\tMD\t_\t_\taux\t_\t_\n        9\tbe\t_\tAUX\tVB\t_\t_\taux\t_\t_\n        10\tcausing\t_\tVERB\tVBG\t_\t_\troot\t_\t_\n        11\tus\t_\tPRON\tPRP\t_\t_\tiobj\t_\t_\n        12\thfgewj\t_\tNOUN\tNN\t_\t_\tdobj\t_\t_\n        13\tfor\t_\tADP\tIN\t_\t_\tcase\t_\t_\n        14\tyears\t_\tNOUN\tNNS\t_\t_\tnmod\t_\t_\n        15\tto\t_\tPART\tTO\t_\t_\tmark\t_\t_\n        16\tcome\t_\tVERB\tVB\t_\t_\tacl\t_\t_\n        17\t.\t_\tPUNCT\t.\t_\t_\tpunct\t_\t_\n        18\t]\t_\tPUNCT\t-RRB-\t_\t_\tpunct\t_\t_\n        '

    def test_diversity_9(self):
        return '\n        1\t[\tPUNCT\t-\t-LRB-\t_\t_\tpunct\t_\t_\n        2\tThis\t_\tDET\tDT\t_\t_\tdet\t_\t_\n        3\twebfguw\t_\tNOUN\tNN\t_\t_\tnsubj\t_\t_\n        4\tof\t_\tADP\tIN\t_\t_\tcase\t_\t_\n        5\ta\t_\tDET\tDT\t_\t_\tdet\t_\t_\n        6\trespected\t_\tADJ\tJJ\t_\t_\tamod\t_\t_\n        7\tcleric\t_\tNOUN\tNN\t_\t_\tnmod\t_\t_\n        8\twill\t_\tAUX\tMD\t_\t_\taux\t_\t_\n        9\tbe\t_\tAUX\tVB\t_\t_\taux\t_\t_\n        10\tcausing\t_\tVERB\tVBG\t_\t_\troot\t_\t_\n        11\tus\t_\tPRON\tPRP\t_\t_\tiobj\t_\t_\n        12\tgvhgww\t_\tNOUN\tNN\t_\t_\tdobj\t_\t_\n        13\tfor\t_\tADP\tIN\t_\t_\tcase\t_\t_\n        14\tyears\t_\tNOUN\tNNS\t_\t_\tnmod\t_\t_\n        15\tto\t_\tPART\tTO\t_\t_\tmark\t_\t_\n        16\tcome\t_\tVERB\tVB\t_\t_\tacl\t_\t_\n        17\t.\t_\tPUNCT\t.\t_\t_\tpunct\t_\t_\n        18\t]\t_\tPUNCT\t-RRB-\t_\t_\tpunct\t_\t_\n        '

    def test_diversity_10(self):
        return '\n        1\t[\tPUNCT\t-\t-LRB-\t_\t_\tpunct\t_\t_\n        2\tThis\t_\tDET\tDT\t_\t_\tdet\t_\t_\n        3\tjhasdg\t_\tNOUN\tNN\t_\t_\tnsubj\t_\t_\n        4\tof\t_\tADP\tIN\t_\t_\tcase\t_\t_\n        5\ta\t_\tDET\tDT\t_\t_\tdet\t_\t_\n        6\trespected\t_\tADJ\tJJ\t_\t_\tamod\t_\t_\n        7\tcleric\t_\tNOUN\tNN\t_\t_\tnmod\t_\t_\n        8\twill\t_\tAUX\tMD\t_\t_\taux\t_\t_\n        9\tbe\t_\tAUX\tVB\t_\t_\taux\t_\t_\n        10\tcausing\t_\tVERB\tVBG\t_\t_\troot\t_\t_\n        11\tus\t_\tPRON\tPRP\t_\t_\tiobj\t_\t_\n        12\tbfwuvru\t_\tNOUN\tNN\t_\t_\tdobj\t_\t_\n        13\tfor\t_\tADP\tIN\t_\t_\tcase\t_\t_\n        14\tyears\t_\tNOUN\tNNS\t_\t_\tnmod\t_\t_\n        15\tto\t_\tPART\tTO\t_\t_\tmark\t_\t_\n        16\tcome\t_\tVERB\tVB\t_\t_\tacl\t_\t_\n        17\t.\t_\tPUNCT\t.\t_\t_\tpunct\t_\t_\n        18\t]\t_\tPUNCT\t-RRB-\t_\t_\tpunct\t_\t_\n        '


class TestsPassing(PassingSystemtests):
    def test_diversity_1(self):
        return '\n1\t[\t_\tPUNCT\t-LRB-\t_\t10\tpunct\t_\t_\n2\tThis\t_\tDET\tDT\t_\t3\tdet\t_\t_\n3\thdsjvjs\t_\tNOUN\tNN\t_\t10\tnsubj\t_\t_\n4\tof\t_\tADP\tIN\t_\t7\tcase\t_\t_\n5\ta\t_\tDET\tDT\t_\t7\tdet\t_\t_\n6\trespected\t_\tADJ\tJJ\t_\t7\tamod\t_\t_\n7\tcleric\t_\tNOUN\tNN\t_\t10\tnmod\t_\t_\n8\twill\t_\tAUX\tMD\t_\t10\taux\t_\t_\n9\tbe\t_\tAUX\tVB\t_\t10\taux\t_\t_\n10\tcausing\t_\tVERB\tVBG\t_\t0\troot\t_\t_\n11\tus\t_\tPRON\tPRP\t_\t10\tiobj\t_\t_\n12\tejhdbhwgjdgw\t_\tNOUN\tNN\t_\t10\tdobj\t_\t_\n13\tfor\t_\tADP\tIN\t_\t14\tcase\t_\t_\n14\tyears\t_\tNOUN\tNNS\t_\t10\tnmod\t_\t_\n15\tto\t_\tPART\tTO\t_\t16\tmark\t_\t_\n16\tcome\t_\tVERB\tVB\t_\t10\tacl\t_\t_\n17\t.\t_\tPUNCT\t.\t_\t10\tpunct\t_\t_\n        '

    def test_diversity_2(self):
        return '\n1\t[\t_\tPUNCT\t-LRB-\t_\t10\tpunct\t_\t_\n2\tThis\t_\tDET\tDT\t_\t3\tdet\t_\t_\n3\tjhdbhcbwjd\t_\tNOUN\tNN\t_\t10\tnsubj\t_\t_\n4\tof\t_\tADP\tIN\t_\t7\tcase\t_\t_\n5\ta\t_\tDET\tDT\t_\t7\tdet\t_\t_\n6\trespected\t_\tADJ\tJJ\t_\t7\tamod\t_\t_\n7\tcleric\t_\tNOUN\tNN\t_\t10\tnmod\t_\t_\n8\twill\t_\tAUX\tMD\t_\t10\taux\t_\t_\n9\tbe\t_\tAUX\tVB\t_\t10\taux\t_\t_\n10\tcausing\t_\tVERB\tVBG\t_\t0\troot\t_\t_\n11\tus\t_\tPRON\tPRP\t_\t10\tiobj\t_\t_\n12\thrwegewbw\t_\tNOUN\tNN\t_\t10\tdobj\t_\t_\n13\tfor\t_\tADP\tIN\t_\t14\tcase\t_\t_\n14\tyears\t_\tNOUN\tNNS\t_\t10\tnmod\t_\t_\n15\tto\t_\tPART\tTO\t_\t16\tmark\t_\t_\n16\tcome\t_\tVERB\tVB\t_\t10\tacl\t_\t_\n17\t.\t_\tPUNCT\t.\t_\t10\tpunct\t_\t_\n        '

    def test_diversity_3(self):
        return '\n1\t[\t_\tPUNCT\t-LRB-\t_\t10\tpunct\t_\t_\n2\tThis\t_\tDET\tDT\t_\t3\tdet\t_\t_\n3\twhjdfgwvdfw\t_\tNOUN\tNN\t_\t10\tnsubj\t_\t_\n4\tof\t_\tADP\tIN\t_\t7\tcase\t_\t_\n5\ta\t_\tDET\tDT\t_\t7\tdet\t_\t_\n6\trespected\t_\tADJ\tJJ\t_\t7\tamod\t_\t_\n7\tcleric\t_\tNOUN\tNN\t_\t10\tnmod\t_\t_\n8\twill\t_\tAUX\tMD\t_\t10\taux\t_\t_\n9\tbe\t_\tAUX\tVB\t_\t10\taux\t_\t_\n10\tcausing\t_\tVERB\tVBG\t_\t0\troot\t_\t_\n11\tus\t_\tPRON\tPRP\t_\t10\tiobj\t_\t_\n12\tfbwejfw\t_\tNOUN\tNN\t_\t10\tdobj\t_\t_\n13\tfor\t_\tADP\tIN\t_\t14\tcase\t_\t_\n14\tyears\t_\tNOUN\tNNS\t_\t10\tnmod\t_\t_\n15\tto\t_\tPART\tTO\t_\t16\tmark\t_\t_\n16\tcome\t_\tVERB\tVB\t_\t10\tacl\t_\t_\n17\t.\t_\tPUNCT\t.\t_\t10\tpunct\t_\t_\n        '

    def test_diversity_4(self):
        return '\n1\t[\t_\tPUNCT\t-LRB-\t_\t10\tpunct\t_\t_\n2\tThis\t_\tDET\tDT\t_\t3\tdet\t_\t_\n3\twbfwjg\t_\tNOUN\tNN\t_\t10\tnsubj\t_\t_\n4\tof\t_\tADP\tIN\t_\t7\tcase\t_\t_\n5\ta\t_\tDET\tDT\t_\t7\tdet\t_\t_\n6\trespected\t_\tADJ\tJJ\t_\t7\tamod\t_\t_\n7\tcleric\t_\tNOUN\tNN\t_\t10\tnmod\t_\t_\n8\twill\t_\tAUX\tMD\t_\t10\taux\t_\t_\n9\tbe\t_\tAUX\tVB\t_\t10\taux\t_\t_\n10\tcausing\t_\tVERB\tVBG\t_\t0\troot\t_\t_\n11\tus\t_\tPRON\tPRP\t_\t10\tiobj\t_\t_\n12\tjhwbghrgfw\t_\tNOUN\tNN\t_\t10\tdobj\t_\t_\n13\tfor\t_\tADP\tIN\t_\t14\tcase\t_\t_\n14\tyears\t_\tNOUN\tNNS\t_\t10\tnmod\t_\t_\n15\tto\t_\tPART\tTO\t_\t16\tmark\t_\t_\n16\tcome\t_\tVERB\tVB\t_\t10\tacl\t_\t_\n17\t.\t_\tPUNCT\t.\t_\t10\tpunct\t_\t_\n        '

    def test_diversity_5(self):
        return '\n1\t[\t_\tPUNCT\t-LRB-\t_\t10\tpunct\t_\t_\n2\tThis\t_\tDET\tDT\t_\t3\tdet\t_\t_\n3\twbjvfvwj\t_\tNOUN\tNN\t_\t10\tnsubj\t_\t_\n4\tof\t_\tADP\tIN\t_\t7\tcase\t_\t_\n5\ta\t_\tDET\tDT\t_\t7\tdet\t_\t_\n6\trespected\t_\tADJ\tJJ\t_\t7\tamod\t_\t_\n7\tcleric\t_\tNOUN\tNN\t_\t10\tnmod\t_\t_\n8\twill\t_\tAUX\tMD\t_\t10\taux\t_\t_\n9\tbe\t_\tAUX\tVB\t_\t10\taux\t_\t_\n10\tcausing\t_\tVERB\tVBG\t_\t0\troot\t_\t_\n11\tus\t_\tPRON\tPRP\t_\t10\tiobj\t_\t_\n12\twebjfw\t_\tNOUN\tNN\t_\t10\tdobj\t_\t_\n13\tfor\t_\tADP\tIN\t_\t14\tcase\t_\t_\n14\tyears\t_\tNOUN\tNNS\t_\t10\tnmod\t_\t_\n15\tto\t_\tPART\tTO\t_\t16\tmark\t_\t_\n16\tcome\t_\tVERB\tVB\t_\t10\tacl\t_\t_\n17\t.\t_\tPUNCT\t.\t_\t10\tpunct\t_\t_\n        '

    def test_diversity_6(self):
        return '\n1\t[\t_\tPUNCT\t-LRB-\t_\t10\tpunct\t_\t_\n2\tThis\t_\tDET\tDT\t_\t3\tdet\t_\t_\n3\twefvghwefvghw\t_\tNOUN\tNN\t_\t10\tnsubj\t_\t_\n4\tof\t_\tADP\tIN\t_\t7\tcase\t_\t_\n5\ta\t_\tDET\tDT\t_\t7\tdet\t_\t_\n6\trespected\t_\tADJ\tJJ\t_\t7\tamod\t_\t_\n7\tcleric\t_\tNOUN\tNN\t_\t10\tnmod\t_\t_\n8\twill\t_\tAUX\tMD\t_\t10\taux\t_\t_\n9\tbe\t_\tAUX\tVB\t_\t10\taux\t_\t_\n10\tcausing\t_\tVERB\tVBG\t_\t0\troot\t_\t_\n11\tus\t_\tPRON\tPRP\t_\t10\tiobj\t_\t_\n12\tjhwefbvgwvufjw\t_\tNOUN\tNN\t_\t10\tdobj\t_\t_\n13\tfor\t_\tADP\tIN\t_\t14\tcase\t_\t_\n14\tyears\t_\tNOUN\tNNS\t_\t10\tnmod\t_\t_\n15\tto\t_\tPART\tTO\t_\t16\tmark\t_\t_\n16\tcome\t_\tVERB\tVB\t_\t10\tacl\t_\t_\n17\t.\t_\tPUNCT\t.\t_\t10\tpunct\t_\t_\n        '

    def test_diversity_7(self):
        return '\n1\t[\t_\tPUNCT\t-LRB-\t_\t10\tpunct\t_\t_\n2\tThis\t_\tDET\tDT\t_\t3\tdet\t_\t_\n3\twebhfvhew\t_\tNOUN\tNN\t_\t10\tnsubj\t_\t_\n4\tof\t_\tADP\tIN\t_\t7\tcase\t_\t_\n5\ta\t_\tDET\tDT\t_\t7\tdet\t_\t_\n6\trespected\t_\tADJ\tJJ\t_\t7\tamod\t_\t_\n7\tcleric\t_\tNOUN\tNN\t_\t10\tnmod\t_\t_\n8\twill\t_\tAUX\tMD\t_\t10\taux\t_\t_\n9\tbe\t_\tAUX\tVB\t_\t10\taux\t_\t_\n10\tcausing\t_\tVERB\tVBG\t_\t0\troot\t_\t_\n11\tus\t_\tPRON\tPRP\t_\t10\tiobj\t_\t_\n12\tjhwgfuw\t_\tNOUN\tNN\t_\t10\tdobj\t_\t_\n13\tfor\t_\tADP\tIN\t_\t14\tcase\t_\t_\n14\tyears\t_\tNOUN\tNNS\t_\t10\tnmod\t_\t_\n15\tto\t_\tPART\tTO\t_\t16\tmark\t_\t_\n16\tcome\t_\tVERB\tVB\t_\t10\tacl\t_\t_\n17\t.\t_\tPUNCT\t.\t_\t10\tpunct\t_\t_\n        '

    def test_diversity_8(self):
        return '\n1\t[\t_\tPUNCT\t-LRB-\t_\t10\tpunct\t_\t_\n2\tThis\t_\tDET\tDT\t_\t3\tdet\t_\t_\n3\tjfvkdfj\t_\tNOUN\tNN\t_\t10\tnsubj\t_\t_\n4\tof\t_\tADP\tIN\t_\t7\tcase\t_\t_\n5\ta\t_\tDET\tDT\t_\t7\tdet\t_\t_\n6\trespected\t_\tADJ\tJJ\t_\t7\tamod\t_\t_\n7\tcleric\t_\tNOUN\tNN\t_\t10\tnmod\t_\t_\n8\twill\t_\tAUX\tMD\t_\t10\taux\t_\t_\n9\tbe\t_\tAUX\tVB\t_\t10\taux\t_\t_\n10\tcausing\t_\tVERB\tVBG\t_\t0\troot\t_\t_\n11\tus\t_\tPRON\tPRP\t_\t10\tiobj\t_\t_\n12\tjhbfewjfhegj\t_\tNOUN\tNN\t_\t10\tdobj\t_\t_\n13\tfor\t_\tADP\tIN\t_\t14\tcase\t_\t_\n14\tyears\t_\tNOUN\tNNS\t_\t10\tnmod\t_\t_\n15\tto\t_\tPART\tTO\t_\t16\tmark\t_\t_\n16\tcome\t_\tVERB\tVB\t_\t10\tacl\t_\t_\n17\t.\t_\tPUNCT\t.\t_\t10\tpunct\t_\t_\n        '

    def test_diversity_9(self):
        return '\n1\t[\t_\tPUNCT\t-LRB-\t_\t10\tpunct\t_\t_\n2\tThis\t_\tDET\tDT\t_\t3\tdet\t_\t_\n3\tjhdhsf\t_\tNOUN\tNN\t_\t10\tnsubj\t_\t_\n4\tof\t_\tADP\tIN\t_\t7\tcase\t_\t_\n5\ta\t_\tDET\tDT\t_\t7\tdet\t_\t_\n6\trespected\t_\tADJ\tJJ\t_\t7\tamod\t_\t_\n7\tcleric\t_\tNOUN\tNN\t_\t10\tnmod\t_\t_\n8\twill\t_\tAUX\tMD\t_\t10\taux\t_\t_\n9\tbe\t_\tAUX\tVB\t_\t10\taux\t_\t_\n10\tcausing\t_\tVERB\tVBG\t_\t0\troot\t_\t_\n11\tus\t_\tPRON\tPRP\t_\t10\tiobj\t_\t_\n12\tgrgtrtgserw\t_\tNOUN\tNN\t_\t10\tdobj\t_\t_\n13\tfor\t_\tADP\tIN\t_\t14\tcase\t_\t_\n14\tyears\t_\tNOUN\tNNS\t_\t10\tnmod\t_\t_\n15\tto\t_\tPART\tTO\t_\t16\tmark\t_\t_\n16\tcome\t_\tVERB\tVB\t_\t10\tacl\t_\t_\n17\t.\t_\tPUNCT\t.\t_\t10\tpunct\t_\t_\n        '

    def test_diversity_10(self):
        return '\n1\t[\t_\tPUNCT\t-LRB-\t_\t10\tpunct\t_\t_\n2\tThis\t_\tDET\tDT\t_\t3\tdet\t_\t_\n3\thgweHGGH\t_\tNOUN\tNN\t_\t10\tnsubj\t_\t_\n4\tof\t_\tADP\tIN\t_\t7\tcase\t_\t_\n5\ta\t_\tDET\tDT\t_\t7\tdet\t_\t_\n6\trespected\t_\tADJ\tJJ\t_\t7\tamod\t_\t_\n7\tcleric\t_\tNOUN\tNN\t_\t10\tnmod\t_\t_\n8\twill\t_\tAUX\tMD\t_\t10\taux\t_\t_\n9\tbe\t_\tAUX\tVB\t_\t10\taux\t_\t_\n10\tcausing\t_\tVERB\tVBG\t_\t0\troot\t_\t_\n11\tus\t_\tPRON\tPRP\t_\t10\tiobj\t_\t_\n12\tegwuewsf\t_\tNOUN\tNN\t_\t10\tdobj\t_\t_\n13\tfor\t_\tADP\tIN\t_\t14\tcase\t_\t_\n14\tyears\t_\tNOUN\tNNS\t_\t10\tnmod\t_\t_\n15\tto\t_\tPART\tTO\t_\t16\tmark\t_\t_\n16\tcome\t_\tVERB\tVB\t_\t10\tacl\t_\t_\n17\t.\t_\tPUNCT\t.\t_\t10\tpunct\t_\t_\n        '
